[WorkplaceEconomy.csv]
Format=Delimited(;)
ColNameHeader=True
Col1=BuildingDefinition Text Width 10
Col2=RequiredCommodity Text Width 5
Col3=RequiredCommodityQuantity Integer Width 1
;Col3=RequiredCommodityQuantity Enumeration 1
Col4=ProcessedCommodity Text Width 5
Col5=ProcessedCommodityQuantity Integer Width 1
Col6=ProcessingTime Integer Width 2
Col7=MinimumWorkersCount Integer Width 1
Col8=MaxWorkersCount Integer Width 2
Col9=CarriersCount Integer Width 1

